carts/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
#auth:zhiyi

from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^index/$',index,name='index'),
    url(r'^carts/$',carts,name='carts'),
    url(r'^add_goods/$',add_goods,name='add_goods'),
    url(r'^goods_num/$',goods_num,name='goods_num'),
    url(r'^edit_goods/$',edit_goods_num,name='edit_goods_num'),
    url(r'^remove_goods/$',remove_goods,name='remove_goods'),
]



if __name__ == '__main__':
    pass

goods/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
#auth:zhiyi

from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^index/$',index,name='index'),
    url(r'^detail/$',detail,name='detail'),
    url(r'^list/(\d+)/(\d+)$',list,name='list'),
    url(r'^goods_chart/$',goods_chart,name='goods_chart')

]



if __name__ == '__main__':
    pass

ttsx/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include # 引入包 转url到应用中的url里
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #以下是url委托
    url(r'^$',RedirectView.as_view(url=r'/goods/index/')),
    url(r'^users/',include('users.urls',namespace='users')), #用户模块
    url(r'^order/',include('order.urls',namespace='order')), #订单模块
    url(r'^carts/',include('carts.urls',namespace='carts')), #购物车模块
    url(r'^goods/',include('goods.urls',namespace='goods')), #商品模块
    url(r'^favicon\.ico$',RedirectView.as_view(url=r'static/favicon.ico'),name='favicon'),
    url(r'^search/',include('haystack.urls')),  #全文搜索
]

goods/models.py
from django.db import models
from db.AbstractModel import *
from tinymce.models import HTMLField


# Create your models here.

class Category(AbstractModel):
    '''
    商品分类类
    '''
    cag_name = models.CharField(max_length=30)  # 分类名称
    cag_image = models.ImageField(upload_to='banner')  # 分类图片


class GoodsInfoManager(models.Manager):
    def get_new_goods(self,cag):
        '''获得最新添加的商品4个'''
        return self.filter(goods_cag=cag).order_by('-id')[:4]

    def get_hot_goods(self,cag):
        return self.filter(goods_cag=cag).order_by('-goods_visits')[:3]

    def get_new_by_all_goods(self):
        return self.all().order_by('-id')[:2]

    def get_goods_by_cagid(self,cag_id,show):
        if show == 'hot':
            return self.filter(goods_cag_id=cag_id).order_by('-goods_visits')
        elif show == 'price':
            return self.filter(goods_cag_id=cag_id).order_by('-goods_price')
        elif show == 'default':
            return self.filter(goods_cag_id=cag_id)


class GoodsInfo(AbstractModel):
    '''
    商品信息类
    '''

    goods_name = models.CharField(max_length=30)  # 商品名称
    goods_price = models.DecimalField(max_digits=10, decimal_places=2)  # 商品价格
    goods_image = models.ImageField(upload_to='goods')  # 商品图片
    goods_short = models.CharField(max_length=100)  # 商品简述
    goods_desc = HTMLField()  # 商品详情
    goods_status = models.BooleanField(default=True)  # 商品上架
    goods_unit = models.CharField(max_length=20)  # 商品单位
    goods_visits = models.IntegerField(default=0)  # 商品访问量
    goods_sales = models.IntegerField(default=0)  # 商品销量
    goods_discount = models.FloatField(default=1.0)  # 商品折扣
    goods_invetory = models.IntegerField(default=0) # 商品库存

    goods_cag = models.ForeignKey(Category)  # 商品所属分类

    objects = GoodsInfoManager()


class Advertise(AbstractModel):
    ad_name = models.CharField(max_length=30)  # 广告名称
    ad_image = models.ImageField(upload_to='adv')  # 广告图片
    ad_link = models.CharField(max_length=200)  # 广告链接

goods/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

# Create your views here.
from goods.models import *
from utils.wrappers import *
from .functions import *
from django.core.paginator import Paginator  # 导入分页


def index(request):
    title= '天天生鲜-首页'
    cags = Category.objects.all() # 获取商品分类
    for cag in cags:
        new_goods = GoodsInfo.objects.get_new_goods(cag) #获得最新商品
        hot_goods = GoodsInfo.objects.get_hot_goods(cag) #获得最热商品

        cag.new = new_goods
        cag.hot = hot_goods

    return render(request,'goods/index.html',locals())

def detail(request):
    '''
    商品详情页
    :param request:
    :return:
    '''
    title= '天天生鲜-商品详情'
    cags = Category.objects.all()  # 获取商品分类
    try:
        goods = GoodsInfo.objects.get(pk=get(request,'id'))
        goods.goods_visits = int(goods.goods_visits) + 1 # 增加一次访问量
        goods.save() # 保存访问量
        #获得最新的商品
        goods_new = GoodsInfo.objects.get_new_by_all_goods()
        update_user_browse_record(request) #更新用户浏览记录
    except:
        return redirect(reverse('goods:index'))
    return render(request,'goods/detail.html',locals())

def list(request,cag_id,page_id):
    title= '天天生鲜-商品列表'
    cags = Category.objects.all() # 获取商品分类
    #根据对应的商品分类获取商品
    show = get(request,'show')
    goods_list = GoodsInfo.objects.get_goods_by_cagid(cag_id,show)

    #分页制作
    paginator = Paginator(goods_list,10) #每页分10个商品

    current_page =paginator.page(page_id)  #获得当前分页数据

    #获取连个最新的广告商品
    goods_new = GoodsInfo.objects.get_new_by_all_goods()

    page_id = int(page_id)  #此处一定要转换类型才可以在模板里进行比较，实现分页高亮效果

    return render(request,'goods/list.html',locals())

def goods_chart(request):
    cags = Category.objects.all()
    cags_list = []
    for cag in cags:
        cags_list.append(cag.cag_name)

    visit_list = []
    for id in range(1,7):
        goods = GoodsInfo.objects.filter(goods_cag_id=id).order_by('-goods_visits')[:5]
        glist = []
        for good in goods:
            glist.append(good.goods_visits)
        visit_list.append(glist)


    return render(request,'goods/goods_chart.html',locals())

templates/goods/detail.html
{# 继承父模板 #}
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load goods_filters %}
{# 头部js #}
{% block header_js %}
    <script>
        $(
            function () {
                function total_price() {
                    var unit_price = parseFloat($(".show_pirze em").html());
                    var counts = parseFloat($("#fruit_num").val());
                    var total = unit_price * counts;

                    return parseFloat(total.toFixed(2)) + ' 元';
                }

                $(".total em").html(total_price());
                $(".add").click(
                    function () {
                        fruit_num = $("#fruit_num");
                        var num = parseInt(fruit_num.val());
                        num += 1;
                        fruit_num.val(num);
                        $(".total em").html(total_price())
                    }
                );
                $(".minus").click(
                    function () {
                        fruit_num = $("#fruit_num");
                        var num = parseInt(fruit_num.val());
                        if (num > 1) {
                            num -= 1;
                        }
                        fruit_num.val(num);
                        $(".total em").html(total_price())
                    }
                );

                $.get('{% url 'carts:goods_num' %}', {}, function (data) {
                    $('#show_count').html(data.total);
                });


            }
        )

    </script>

{% endblock header_js %}

{% block body %}
    {# 上方用户状态条 #}
    {% include 'common/status.html' %}

     {# logo 搜索 购物车 #}
    {% include 'goods/goods_search_bar.html' %}

    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    <li><a href="{% url 'goods:list' cags.0.id 1 %}?show=default"
                           class="fruit">{{ cags.0.cag_name }}</a></li>
                    <li><a href="{% url 'goods:list' cags.1.id 1 %}?show=default"
                           class="seafood">{{ cags.1.cag_name }}</a></li>
                    <li><a href="{% url 'goods:list' cags.2.id 1 %}?show=default" class="meet">{{ cags.2.cag_name }}</a>
                    </li>
                    <li><a href="{% url 'goods:list' cags.3.id 1 %}?show=default" class="egg">{{ cags.3.cag_name }}</a>
                    </li>
                    <li><a href="{% url 'goods:list' cags.4.id 1 %}?show=default"
                           class="vegetables">{{ cags.4.cag_name }}</a></li>
                    <li><a href="{% url 'goods:list' cags.5.id 1 %}?show=default" class="ice">{{ cags.5.cag_name }}</a>
                    </li>
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">新鲜水果</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{% static goods.goods_image|create_goods_image_name %}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ goods.goods_name }}</h3>
            <p>{{ goods.goods_short }}</p>
            <input type="hidden" value="{{ goods.id }}" id="goods_id">
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ goods.goods_price }}</em></span>
                <span class="show_unit">单  位：{{ goods.goods_unit }}</span>
            </div>
            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input type="text" id="fruit_num" class="num_show fl" value="1">
                    <a href="javascript:;" class="add fr">+</a>
                    <a href="javascript:;" class="minus fr">-</a>
                </div>
            </div>
            <div class="total">总价：<em>16.80元</em></div>
            <div class="operate_btn">
                <a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    <li>
                        {% for goods in goods_new %}
                            <a href="{% url 'goods:detail' %}?id={{ goods.id }}"><img
                                    src="{% static goods.goods_image|create_goods_image_name %}"></a>
                            <h4><a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a></h4>
                            <div class="prize">￥{{ goods.goods_price }}</div>
                        {% endfor %}
                    </li>
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li class="active">商品介绍</li>
                <li>评论</li>
            </ul>

            <div class="tab_content">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>{{ goods.goods_desc }}
                    </dd>
                </dl>
            </div>

        </div>
    </div>
{% endblock body %}

{% block footer_js %}
    <script type="text/javascript">

        $('#add_cart').click(function () {
            var $add_x = $('#add_cart').offset().top;
            var $add_y = $('#add_cart').offset().left;

            var $to_x = $('#show_count').offset().top;
            var $to_y = $('#show_count').offset().left;

            $(".add_jump").css({'left': $add_y + 80, 'top': $add_x + 10, 'display': 'block'});

            $(".add_jump").stop().animate({
                    'left': $to_y + 7,
                    'top': $to_x + 7
                },
                "fast", function () {
                    $(".add_jump").fadeOut('fast', function () {
                        // $('#show_count').html(2);
                        ;
                    });

                });

            var goods_id = $("#goods_id").val();
            var goods_num = $("#fruit_num").val();

            $.get('{% url 'carts:add_goods' %}', {'goods_id': goods_id, 'goods_num': goods_num}, function (data) {
                $('#show_count').html(data.total);
            })

        })
    </script>
{% endblock footer_js %}

templates/goods/goods_chart.html
{# 继承父模板 #}
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load goods_filters %}
{% block header_css %}
    <style>
{#        #container {#}
{#            height: 400px;#}
{#            width: 600px;#}
{#            margin: 100px 100px;#}
{#        }#}
    </style>
{% endblock header_css %}
{% block body %}
    <span style="display: none" id="cags_list">{{ cags_list }}</span>
    <span id="top5_fruit" style="display: none">{{ visit_list }}</span>
    <div id="container">


    </div>
{% endblock body %}
{# 网底部的JS部分 #}
{% block footer_js %}
    <script>
            $(function () {
    $('#container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: '商品访问量'
        },
        subtitle: {
            text: '数据来源: mysql数据库'
        },
        xAxis: {
            categories: ['第一名','第二名','第三名','第四名','第五名'],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: '访问量 (次)'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.f} 次</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: '新鲜水果',
            data: eval($('#top5_fruit').html())[0]
        }, {
            name: '海鲜水产',
            data:  eval($('#top5_fruit').html())[1]
        }, {
            name: '猪牛羊肉',
            data:  eval($('#top5_fruit').html())[2]
        }, {
            name: '禽类单品',
            data:  eval($('#top5_fruit').html())[3]
        },{
            name: '新鲜蔬菜',
            data: eval($('#top5_fruit').html())[4]
        },{
            name: '速冻食品',
            data: eval($('#top5_fruit').html())[5]
        }
        ]
    });
});


    </script>
{% endblock footer_js %}

templates/goods/goods_search_bar.html
{% load staticfiles %}
<div class="search_bar clearfix">
    <a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
    <form method="get" action="/search/">
        <div class="search_con fl">
            <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
            <input type="submit" class="input_btn fr" value="搜索">
        </div>
    </form>
    <div class="guest_cart fr">
        <a href="{% url 'carts:carts' %}" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count"></div>
    </div>
</div>

templates/goods/index.html
{# 继承父模板 #}
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load goods_filters %}
{% block body %}
    {# 上方用户状态条 #}
    {% include 'common/status.html' %}
    {# logo 搜索 购物车 #}
    {% include 'goods/goods_search_bar.html' %}

    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
                <li class="interval">|</li>
                <li><a href="{% url 'goods:goods_chart' %}">热门商品</a></li>
            </ul>
        </div>
    </div>

    <div class="center_con clearfix">
        <ul class="subnav fl">
            <li><a href="{% url 'goods:list' cags.0.id 1 %}?show=default" class="fruit">{{ cags.0.cag_name }}</a></li>
            <li><a href="{% url 'goods:list' cags.1.id 1 %}?show=default" class="seafood">{{ cags.1.cag_name }}</a></li>
            <li><a href="{% url 'goods:list' cags.2.id 1 %}?show=default" class="meet">{{ cags.2.cag_name }}</a></li>
            <li><a href="{% url 'goods:list' cags.3.id 1 %}?show=default" class="egg">{{ cags.3.cag_name }}</a></li>
            <li><a href="{% url 'goods:list' cags.4.id 1 %}?show=default" class="vegetables">{{ cags.4.cag_name }}</a>
            </li>
            <li><a href="{% url 'goods:list' cags.5.id 1 %}?show=default" class="ice">{{ cags.5.cag_name }}</a></li>
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                <li><img src="{% static 'images/slide/slide01.jpg' %}" alt="幻灯片"></li>
                <li><img src="{% static 'images/slide/slide02.jpg' %}" alt="幻灯片"></li>
                <li><img src="{% static 'images/slide/slide03.jpg' %}" alt="幻灯片"></li>
                <li><img src="{% static 'images/slide/slide04.jpg' %}" alt="幻灯片"></li>
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            <a href="#"><img src="{% static 'images/adv/adv01.jpg' %}"></a>
            <a href="#"><img src="{% static 'images/adv/adv02.jpg' %}"></a>
        </div>
    </div>

    {% for cag in cags %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl" id="model01">{{ cag.cag_name }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {# 显示热门的商品 #}
                    {% for goods in cag.hot %}
                        <a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a>
                    {% endfor %}
                </div>
                <a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="{% static cag.cag_image|create_banner_image_name %}"></div>
                <ul class="goods_list fl">
                    {% for goods in cag.new %}
                        <li>
                            <h4><a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a></h4>
                            <a href="{% url 'goods:detail' %}?id={{ goods.id }}"><img
                                    src="{% static goods.goods_image|create_goods_image_name %}"></a>
                            <div class="prize">¥ {{ goods.goods_price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}

{% endblock body %}
{# 网底部的JS部分 #}
{% block footer_js %}

    <script type="text/javascript">
        $.get('{% url 'carts:goods_num' %}', {}, function (data) {
            $('#show_count').html(data.total);
        });
        BCSlideshow('focuspic');
        var oFruit = document.getElementById('fruit_more');
        var oShownum = document.getElementById('show_count');

        var hasorder = localStorage.getItem('order_finish');

        if (hasorder) {
            oShownum.innerHTML = '2';
        }

        oFruit.onclick = function () {
            window.location.href = 'list.html';
        };


    </script>
{% endblock footer_js %}

templates/goods/list.html
{# 继承父模板 #}
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load goods_filters %}
{% block body %}
    {# 上方用户状态条 #}
    {% include 'common/status.html' %}

    {# logo 搜索 购物车 #}
    {% include 'goods/goods_search_bar.html' %}

    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    <li><a href="{% url 'goods:list' cags.0.id 1 %}?show=default"
                           class="fruit">{{ cags.0.cag_name }}</a></li>
                    <li><a href="{% url 'goods:list' cags.1.id 1 %}?show=default"
                           class="seafood">{{ cags.1.cag_name }}</a></li>
                    <li><a href="{% url 'goods:list' cags.2.id 1 %}?show=default" class="meet">{{ cags.2.cag_name }}</a>
                    </li>
                    <li><a href="{% url 'goods:list' cags.3.id 1 %}?show=default" class="egg">{{ cags.3.cag_name }}</a>
                    </li>
                    <li><a href="{% url 'goods:list' cags.4.id 1 %}?show=default"
                           class="vegetables">{{ cags.4.cag_name }}</a></li>
                    <li><a href="{% url 'goods:list' cags.5.id 1 %}?show=default" class="ice">{{ cags.5.cag_name }}</a>
                    </li>
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">新鲜水果</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for goods in goods_new %}
                        <li>
                            <a href="{% url 'goods:detail' %}?id={{ goods.id }}"><img
                                    src="{% static goods.goods_image|create_goods_image_name %}"></a>
                            <h4><a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a></h4>
                            <div class="prize">￥{{ goods.goods_price }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                <a href="{% url 'goods:list'  cag_id 1 %}?show=default"
                   {% if show == 'default' %}class="active" {% endif %}>默认</a>
                <a href="{% url 'goods:list'  cag_id 1 %}?show=price"
                   {% if show == 'price' %}class="active" {% endif %}>价格</a>
                <a href="{% url 'goods:list'  cag_id 1 %}?show=hot"
                   {% if show == 'hot' %}class="active" {% endif %}>人气</a>
            </div>

            <ul class="goods_type_list clearfix">

                {% for goods in current_page %}
                    <li>
                        <a href="{% url 'goods:detail' %}?id={{ goods.id }}"><img
                                src="{% static goods.goods_image|create_goods_image_name %}"></a>
                        <h4><a href="{% url 'goods:detail' %}?id={{ goods.id }}">{{ goods.goods_name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ goods.goods_price }}</span>
                            <span class="unit">{{ goods.goods_price }}/{{ goods.goods_unit }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}

            </ul>

            <div class="pagenation">
                {% if current_page.has_previous %}
                    <a href="{% url 'goods:list' cag_id current_page.previous_page_number %}?show={{ show }}">
                        &lt;上一页
                    </a>
                {% endif %}
                {% for index in paginator.page_range %}
                    <a href="{% url 'goods:list' cag_id index %}?show={{ show }}"
                       {% if page_id == index %}class="active"{% endif %}>{{ index }}</a>
                {% endfor %}
                {% if current_page.has_next %}
                    <a href="{% url 'goods:list' cag_id current_page.next_page_number %}?show={{ show }}">下一页&gt;</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock body %}

{% block footer_js %}

    <script type="text/javascript">
        $.get('{% url 'carts:goods_num' %}', {}, function (data) {
            $('#show_count').html(data.total);
        });
    </script>
{% endblock footer_js %}