carts/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
#auth:zhiyi

from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^index/$',index,name='index'),
    url(r'^carts/$',carts,name='carts'),
    url(r'^add_goods/$',add_goods,name='add_goods'),
    url(r'^goods_num/$',goods_num,name='goods_num'),
    url(r'^edit_goods/$',edit_goods_num,name='edit_goods_num'),
    url(r'^remove_goods/$',remove_goods,name='remove_goods'),
]



if __name__ == '__main__':
    pass

ttsx/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include # 引入包 转url到应用中的url里
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #以下是url委托
    url(r'^$',RedirectView.as_view(url=r'/goods/index/')),
    url(r'^users/',include('users.urls',namespace='users')), #用户模块
    url(r'^order/',include('order.urls',namespace='order')), #订单模块
    url(r'^carts/',include('carts.urls',namespace='carts')), #购物车模块
    url(r'^goods/',include('goods.urls',namespace='goods')), #商品模块
    url(r'^favicon\.ico$',RedirectView.as_view(url=r'static/favicon.ico'),name='favicon'),
    url(r'^search/',include('haystack.urls')),  #全文搜索
]

users/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
#auth:zhiyi

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^login_handle/$',views.login_handle,name='login_handle'),#处理登录请求
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^register/',views.register,name='register'),
    url(r'^user_center_info/',views.user_center_info,name='user_center_info'),
    url(r'^user_center_order/',views.user_center_order,name='user_center_order'),
    url(r'^user_center_site/',views.user_center_site,name='user_center_site'),
    #处理用户注册
    url(r'^register_handle/$',views.register_handle,name='register_handle'),
    #检测用户名是否存在的ajax请求
    url(r'check_username',views.check_username,name='check_username'),
    url(r'^user_addr_edit/$',views.user_addr_edit,name='user_addr_edit')
]



if __name__ == '__main__':
    pass

templates/common/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><!--设置字符集-->
    <!--设置视口，用于手机浏览-->
    <meta name="viewport"
          content="width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
    <!--兼容IE浏览器-->
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--引入reset.css 清除元素默认效果-->
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <!--引入主css效果-->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{#    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">#}
    <link rel="shortcut icon" href="{% url 'favicon' %}">
    <!--引入jquery-->
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <!--引入为了兼容低版本ie的json-->
    <script type="text/javascript" src="{% static 'js/json2.js' %}"></script>
    <!--引入jquery操作cookie-->
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js'%}"></script>
    <!--引入jquery鼠标滚动支持-->
    <script type="text/javascript" src="{% static 'js/jquery.mousewheel.js' %}"></script>

    <!--添加动画支持颜色-->
    <script type="text/javascript" src="{% static 'js/jquery.animate-colors-min.js' %}"></script>

    <!--引入heightchart-->
    <script type="text/javascript" src="{% static 'js/heightchart/highcharts.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/heightchart/modules/exporting.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    <!--网页的标题-->
    <title>{{ title }}</title>
    <style></style><!--页内的css-->
    {% block header_css %}{% endblock header_css %}
    <script>
        //页内的js
        $(function () {  //js ready

        });
    </script>
    {# 头部的JS部分 #}
    {% block header_js %}{% endblock header_js %}


</head>
<body>
    {# 网页的主题部分 #}

    {% block body %}

    {% endblock body %}

    {% include 'common/footer.html' %}

    {# 网底部的JS部分 #}
    {% block footer_js %}{% endblock footer_js %}
</body>
</html>

templates/common/footer.html
<div class="footer {% block footer_css %}{% endblock %}">

    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
<div class="add_jump"></div>

templates/common/status.html
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            {% if request.session.username %}
            <div class="login_btn fl">
                欢迎您：<em>{{ request.session.username }}</em>
                <span>|</span>
                <a href="{% url 'users:logout' %}">注销</a>
            </div>
            {% else %}
            <div class="login_btn fl">
                <a href="{% url 'users:login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'users:register' %}">注册</a>
            </div>
            {% endif %}

            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'users:user_center_info' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'carts:carts' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'users:user_center_order' %}">我的订单</a>
            </div>
        </div>
    </div>
</div>