goods/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
#auth:zhiyi

from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^index/$',index,name='index'),
    url(r'^detail/$',detail,name='detail'),
    url(r'^list/(\d+)/(\d+)$',list,name='list'),
    url(r'^goods_chart/$',goods_chart,name='goods_chart')

]



if __name__ == '__main__':
    pass

ttsx/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include # 引入包 转url到应用中的url里
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #以下是url委托
    url(r'^$',RedirectView.as_view(url=r'/goods/index/')),
    url(r'^users/',include('users.urls',namespace='users')), #用户模块
    url(r'^order/',include('order.urls',namespace='order')), #订单模块
    url(r'^carts/',include('carts.urls',namespace='carts')), #购物车模块
    url(r'^goods/',include('goods.urls',namespace='goods')), #商品模块
    url(r'^favicon\.ico$',RedirectView.as_view(url=r'static/favicon.ico'),name='favicon'),
    url(r'^search/',include('haystack.urls')),  #全文搜索
]

users/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
#auth:zhiyi

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^login_handle/$',views.login_handle,name='login_handle'),#处理登录请求
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^register/',views.register,name='register'),
    url(r'^user_center_info/',views.user_center_info,name='user_center_info'),
    url(r'^user_center_order/',views.user_center_order,name='user_center_order'),
    url(r'^user_center_site/',views.user_center_site,name='user_center_site'),
    #处理用户注册
    url(r'^register_handle/$',views.register_handle,name='register_handle'),
    #检测用户名是否存在的ajax请求
    url(r'check_username',views.check_username,name='check_username'),
    url(r'^user_addr_edit/$',views.user_addr_edit,name='user_addr_edit')
]



if __name__ == '__main__':
    pass

order/models.py
from django.db import models
from db.AbstractModel import *
# Create your models here.

class OrderDetail(AbstractModel):
    detail_name = models.CharField(max_length=50) # 商品名称
    detail_price = models.DecimalField(max_digits=10, decimal_places=2)  #商品价格
    detail_amount = models.IntegerField() #商品数量
    detail_unit = models.CharField(max_length=20)
    detail_img = models.ImageField(upload_to='goods')
    detail_goodsid = models.IntegerField()
    order = models.ForeignKey('order.Order')



class Order(AbstractModel):
    status = (
        (1,'待付费'),
        (2,'待发货'),
        (3,'待收货'),
        (4,'待完成'),
    )

    pay = (
        (1,'货到付款'),
        (2,'微信支付'),
        (3,'支付宝支付'),
        (4,'银联支付'),
    )

    order_number = models.CharField(max_length=50) # 订单编号
    order_addr = models.CharField(max_length=100)  # 收货地址
    order_recv = models.CharField(max_length=10)  # 收货人
    order_fee = models.DecimalField(default=10,decimal_places=2,max_digits=10)  # 运费
    order_status = models.SmallIntegerField(choices=status,default=1)#送货方式
    order_pay = models.SmallIntegerField(choices=pay,default=1) # 支付方式
    order_user = models.ForeignKey('users.User')  # 订单商品列表

users/models.py
from django.db import models
from db.AbstractModel import *
# Create your models here.
from utils.wrappers import *
import random


class UserManager(models.Manager):
    '''自定义管理器类'''
    def get_user_by_name(self,username):
        try:
            return self.get(user_name=username)
        except:
            return None

    #用户注册数据保存
    def user_register_save(self,request):
        user = User()
        user.user_name = post(request,'user_name')
        user.user_salt = random.randint(100000,999999)
        user.user_pass = password_encryption(post(request,'user_pass1'),user.user_salt)
        user.user_mail = post(request,'user_mail')
        user.save()

    def user_addr_update(self,request):
        user = self.get_user_by_name(get_session(request,'username'))  # 获得用户
        #更新用户地址信息
        user.user_recv = post(request, 'user_recv')
        user.user_addr = post(request, 'user_addr')
        user.user_code = post(request, 'user_code')
        user.user_tele = post(request, 'user_tele')
        # 保存数据
        user.save()


#用户模型类
class User(AbstractModel):
    user_name = models.CharField(max_length=20)  #用户名
    user_pass = models.CharField(max_length=100) #用户密码
    user_mail = models.CharField(max_length=50)  #用户邮箱
    user_addr = models.CharField(max_length=50)  #用户地址
    user_tele = models.CharField(max_length=11)  #用户手机
    user_code = models.CharField(max_length=10)   #邮政编码
    user_salt = models.CharField(max_length=6)  #用户salt
    user_recv = models.CharField(max_length=20,default='') #收件人姓名

    objects = UserManager()

#用户浏览记录
class UserBrowseHistory(AbstractModel):
    browse_goods = models.ForeignKey('goods.GoodsInfo')
    browse_user = models.ForeignKey('users.User')

users/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
# Create your views here.
from django.http import HttpResponse,JsonResponse
from .functions import *
from django.contrib import messages
from order.models import *



def index(request):
    return HttpResponse('ok')


def login(request):  # 登录页面的逻辑
    title = '天天生鲜-登录'
    return render(request, 'users/login.html', locals())

def login_handle(request):
    '''
    用于处理登录请求
    :param request:
    :return:
    '''
    #1.对用户名和密码做简单的校验
    print('1111')
    user = check_login_params(request)
    if user:
        print('222')
        response = auth_user(request,user)
        return response
    else:
        print('333')
        return  redirect(reverse('users:login'))# 如果用户名和密码简单校验失败则直接重回登录页面

def logout(request):
    '''
    注销操作
    :param request:
    :return:
    '''
    # 1.清除session
    flush_session(request)
    # 2.页面跳转
    return redirect(reverse('users:login'))

def register(request):
    title = '天天生鲜-注册'
    mess = get_messages(request)  # 取出错误信息
    return render(request, 'users/register.html', locals())

def register_handle(request):  # 处理注册
    '''
     #检测注册参数是否合法
    :param request: 请求
    :return: 成功 数据入库返回登录页面 失败重新跳转注册页面
    '''
    if check_register_params(request):
        User.objects.user_register_save(request)  # 合法 用户入库
        print('用户合法')
        return redirect(reverse('users:login'))  # 跳转到登录页面
    else:
        # 如何验证失败，跳回验证页面
        print('用户不合法')
        return redirect(reverse('users:register'))

@check_permission
def user_center_info(request):
    title = '天天生鲜-用户中心'
    current_user = User.objects.get_user_by_name(get_session(request,'username'))
    #records = UserBrowseHistory.objects.filter(browse_user=get_session(request,'uid')).order_by('-update_time')
    return render(request, 'users/user_center_info.html', locals())

@check_permission
def user_center_order(request):
    title = '天天生鲜-用户订单'
    my_orders = Order.objects.filter(order_user_id=get_session(request,'uid'))
    paginator = Paginator(my_orders,3)#分页
    current_page = get(request,'page')
    if not current_page:
        current_page = 1
    my_orders = paginator.page(current_page)
    for order in my_orders:
        order.total = 0
        for goods in order.orderdetail_set.all():
            order.total += goods.detail_amount * goods.detail_price


    return render(request, 'users/user_center_order.html', locals())

@check_permission
def user_center_site(request):
    title = '天天生鲜-用户地址'
    current_user = User.objects.get_user_by_name(get_session(request,'username'))
    userrecv = current_user.user_recv
    useraddr = current_user.user_addr
    usercode = current_user.user_code
    usertele = current_user.user_tele
    usertele2 = usertele[:3] + '****' + usertele[-4:]
    return render(request, 'users/user_center_site.html', locals())


def check_username(request):
    '''
    检查用户名密码是否存在
    :param request:
    :return:
    '''
    if user_is_exist(request):
        return JsonResponse({'ret':1})
    else:
        return JsonResponse({'ret':0})

@check_permission
def user_addr_edit(request):
    '''
    更新用户信息
    :param request:
    :return:
    '''
    if check_addr_param(request):
        User.objects.user_addr_update(request)
    return redirect(reverse('users:user_center_site'))

templates/users/common_left_menu.html
{% load users_filters %}
<div class="left_menu_con clearfix">
    <h3>用户中心</h3>
    <ul>
        {# 根据传入的内容创建菜单 #}
        {% with menus=flag|create_user_center_left_menu %}
        {% for menu in menus %}
        <li><a href="{{ menu.link }}" class="{{ menu.active }}">{{ menu.name }}</a></li>
            {% endfor %}
        {% endwith %}
    </ul>
</div>

templates/users/login.html
{# 继承父模板 #}
{% extends 'common/base.html' %}
{% load staticfiles %}

{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="{% url 'users:login_handle' %}">
                        {% csrf_token %}
						<input type="text" name="user_name" class="name_input" value="{{ request.COOKIES.username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="user_pass" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="user_remb">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{%  endblock body %}
{% block footer_css %}no-mp{% endblock %}

templates/users/register.html
{# 继承父模板 #}
{% extends 'common/base.html' %}
{% load staticfiles %}


{% block header_js %}
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock header_js %}

{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
            <div class="reg_slogan">足不出户 · 新鲜每一天</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="{% url 'users:login' %}">登录</a>
            </div>
            <div class="reg_form clearfix" >
                <form method="post" id="reg_form" action="{% url 'users:register_handle' %}">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                            <span class="error_tip_info" >{{ mess.user_name_err }}</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="user_pass1" id="pwd">
                            <span class="error_tip">提示信息</span>
                            <span class="error_tip_info" >{{ mess.user_pass_err }}</span>

                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="user_pass2" id="cpwd">
                            <span class="error_tip">提示信息</span>
                            <span class="error_tip_info">{{ mess.user_pass_diff_err }}</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="user_mail" id="email">
                            <span class="error_tip">提示信息</span>
                            <span class="error_tip_info">{{ mess.user_mail_err }}</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="user_allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册">
                        </li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}
{% block footer_css %}no-mp{% endblock %}

templates/users/user_center_info.html
{# 继承父模板 #}
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load goods_filters %}
{% block body %}
    {# 上方用户状态条 #}
    {% include 'common/status.html' %}

    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
      <form method="get" action="/search/">
    <div class="search_con fr">
        <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
        <input type="submit" class="input_btn fr" value="搜索">
    </div></form>
    </div>

    <div class="main_con clearfix">
        {# 左侧菜单 #}
        {% include 'users/common_left_menu.html' with flag='info' %}
        <div class="right_content clearfix">
            <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                <ul class="user_info_list">
                    <li><span>收件人：</span>{{ current_user.user_recv|default:'未填写' }}</li>
                    <li><span>联系方式：</span>{{ current_user.user_tele|default:'未填写' }}</li>
                    <li><span>联系地址：</span>{{ current_user.user_addr|default:'未填写' }}</li>
                </ul>
            </div>

            <h3 class="common_title2">最近浏览</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    {% for recode in current_user.userbrowsehistory_set.all|browse_history_sort %}
                        <li>
                            <a href="{% url 'goods:detail' %}?id={{ recode.browse_goods.id }}">
                                <img src="{% static recode.browse_goods.goods_image|create_goods_image_name %}"></a>
                            <h4>
                                <a href="{% url 'goods:detail' %}?id={{ recode.browse_goods.id }}">{{ recode.browse_goods.goods_name }}</a>
                            </h4>
                            <div class="operate">
                                <span class="prize">￥{{ recode.browse_goods.goods_price }} </span>
                                <span class="unit">{{ recode.browse_goods.goods_price }}/{{ recode.browse_goods.goods_unit }}"</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
{% endblock body %}

templates/users/user_center_order.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load goods_filters %}
{% block body %}
    {# 上方用户状态条 #}
    {% include 'common/status.html' %}

    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <form method="get" action="/search/">
            <div class="search_con fr">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" value="搜索">
            </div>
        </form>
    </div>

    <div class="main_con clearfix">
        {# 左侧菜单 #}
        {% include 'users/common_left_menu.html' with flag='order' %}
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>

            {% for order in my_orders %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.update_time }}</li>
                    <li class="col02">订单号：{{ order.order_number }}</li>
                    <li class="col02 stress">
                        {% if order.order_status == 1 %}
                            待支付
                        {% elif order.order_status == 2 %}
                            待发货
                        {% elif order.order_status == 3 %}
                            待收货
                        {% elif order.order_status == 4 %}
                            已完成
                        {% endif %}
                    </li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {% for goods in order.orderdetail_set.all %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{% static goods.detail_img|create_goods_image_name %}">
                                    </li>
                                    <li class="col02">{{ goods.detail_name }}<em>{{ goods.detail_price }}元/{{ goods.detail_unit }}</em>
                                    </li>
                                    <li class="col03">{{ goods.detail_amount }}</li>
                                    <li class="col04">{{ goods.detail_price }}元</li>
                                </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total }}元</td>
                        <td width="15%">
                            {% if order.order_status == 1 %}
                                待支付
                            {% elif order.order_status == 2 %}
                                待发货
                            {% elif order.order_status == 3 %}
                                待收货
                            {% elif order.order_status == 4 %}
                                已完成
                            {% endif %}
                        </td>
                        <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}


            <div class="pagenation">
                {% if my_orders.has_previous %}
                    <a href="?page={{ my_orders.previous_page_number }}">
                        &lt;上一页
                    </a>
                {% endif %}
                {% for index in paginator.page_range %}
                    <a href="?page={{ index }}"
                       {% if index == my_orders.number %}class="active"{% endif %}>{{ index }}</a>
                {% endfor %}
                {% if my_orders.has_next %}
                    <a href="?page={{ my_orders.next_page_number }}">下一页&gt;</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock body %}

templates/users/user_center_site.html
{# 继承父模板 #}
{% extends 'common/base.html' %}
{% load staticfiles %}
{% block body %}
    {# 上方用户状态条 #}
    {% include 'common/status.html' %}

    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <form method="get" action="/search/">
            <div class="search_con fr">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" value="搜索">
            </div>
        </form>
    </div>

    <div class="main_con clearfix">
        {# 左侧菜单 #}
        {% include 'users/common_left_menu.html' with flag='site' %}
        <div class="right_content clearfix">
            <h3 class="common_title2">收货地址</h3>
            <div class="site_con">
                <dl>
                    <dt>当前地址：</dt>
                    <dd>{{ useraddr|default:'尚未填写地址' }} （{{ userrecv|default:'未填写收件人' }}
                        收） {{ usertele2|default:'未填写手机号码' }}</dd>
                </dl>
            </div>
            <h3 class="common_title2">编辑地址</h3>
            <div class="site_con">
                <form method="post" action="{% url 'users:user_addr_edit' %}">
                    {% csrf_token %}
                    <div class="form_group">
                        <label>收件人：</label>
                        <input type="text" value="{{ userrecv|default:'未填写' }}" name="user_recv">
                    </div>
                    <div class="form_group form_group2">
                        <label>详细地址：</label>
                        <textarea class="site_area" name="user_addr">{{ useraddr|default:'未填写' }} </textarea>
                    </div>
                    <div class="form_group">
                        <label>邮编：</label>
                        <input type="text" value="{{ usercode|default:'未填写' }}" name="user_code">
                    </div>
                    <div class="form_group">
                        <label>手机：</label>
                        <input type="text" value="{{ usertele|default:'未填写' }}" name="user_tele">
                    </div>
                    <input type="submit" value="提交" class="info_submit">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}