order/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
#auth:zhiyi

from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^index/$',index,name='index'),
    url(r'^place_order/$',place_order,name='place_order'),
    url(r'^order_handle/$',order_handle,name='order_handle'),
]



if __name__ == '__main__':
    pass

ttsx/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include # 引入包 转url到应用中的url里
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #以下是url委托
    url(r'^$',RedirectView.as_view(url=r'/goods/index/')),
    url(r'^users/',include('users.urls',namespace='users')), #用户模块
    url(r'^order/',include('order.urls',namespace='order')), #订单模块
    url(r'^carts/',include('carts.urls',namespace='carts')), #购物车模块
    url(r'^goods/',include('goods.urls',namespace='goods')), #商品模块
    url(r'^favicon\.ico$',RedirectView.as_view(url=r'static/favicon.ico'),name='favicon'),
    url(r'^search/',include('haystack.urls')),  #全文搜索
]

users/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
#auth:zhiyi

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^login_handle/$',views.login_handle,name='login_handle'),#处理登录请求
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^register/',views.register,name='register'),
    url(r'^user_center_info/',views.user_center_info,name='user_center_info'),
    url(r'^user_center_order/',views.user_center_order,name='user_center_order'),
    url(r'^user_center_site/',views.user_center_site,name='user_center_site'),
    #处理用户注册
    url(r'^register_handle/$',views.register_handle,name='register_handle'),
    #检测用户名是否存在的ajax请求
    url(r'check_username',views.check_username,name='check_username'),
    url(r'^user_addr_edit/$',views.user_addr_edit,name='user_addr_edit')
]



if __name__ == '__main__':
    pass

order/models.py
from django.db import models
from db.AbstractModel import *
# Create your models here.

class OrderDetail(AbstractModel):
    detail_name = models.CharField(max_length=50) # 商品名称
    detail_price = models.DecimalField(max_digits=10, decimal_places=2)  #商品价格
    detail_amount = models.IntegerField() #商品数量
    detail_unit = models.CharField(max_length=20)
    detail_img = models.ImageField(upload_to='goods')
    detail_goodsid = models.IntegerField()
    order = models.ForeignKey('order.Order')



class Order(AbstractModel):
    status = (
        (1,'待付费'),
        (2,'待发货'),
        (3,'待收货'),
        (4,'待完成'),
    )

    pay = (
        (1,'货到付款'),
        (2,'微信支付'),
        (3,'支付宝支付'),
        (4,'银联支付'),
    )

    order_number = models.CharField(max_length=50) # 订单编号
    order_addr = models.CharField(max_length=100)  # 收货地址
    order_recv = models.CharField(max_length=10)  # 收货人
    order_fee = models.DecimalField(default=10,decimal_places=2,max_digits=10)  # 运费
    order_status = models.SmallIntegerField(choices=status,default=1)#送货方式
    order_pay = models.SmallIntegerField(choices=pay,default=1) # 支付方式
    order_user = models.ForeignKey('users.User')  # 订单商品列表

order/views.py
import time

from django.shortcuts import render
from django.db import transaction  #事务支持
# Create your views here.
from django.http import HttpResponse,JsonResponse


# Create your views here.
from carts.models import *
from order.models import *
from utils.wrappers import *
from users.models import *


def index(request):
    return HttpResponse('ok')

@check_permission
def place_order(request):
    title = '天天生鲜-提交订单'
    try:
        user = User.objects.get(id=get_session(request,'uid'))
    except User.DoesNotExist:
        return redirect(reverse('order:place_order'))

    # 提交订单时 购物车里选中的商品的id列表
    goods_ids = post_list(request,'goods_id')
    #print(goods_ids)
    goods_ids_string = ','.join(goods_ids)  #将提交的商品ID拼接成 ，隔开的字符串


    carts = Cart.objects.filter(cart_user_id=get_session(request,'uid'),cart_goods_id__in=goods_ids)
    total_nums = 0 #用于累计商品总数
    total_money = 0 #用于累计商品总价
    for cart in carts:
        #计算单品总价
        cart.total = cart.cart_amount * cart.cart_goods.goods_price
        total_money += cart.total
        total_nums += cart.cart_amount
    #绑定总价
    carts.total_money = total_money
    carts.total_nums = total_nums


    return render(request,'order/place_order.html',locals())


@check_permission
@transaction.atomic #当做事务函数处理
def order_handle(request):
    save_point = transaction.savepoint() #创建回滚点

    try:
        ids = post(request,'ids').split(',') # 获取订单商品
        goods_pay = post(request,'pay')  #获取订单支付方式
        #获取商品详细信息
        carts = Cart.objects.filter(cart_user_id=get_session(request,'uid'),cart_goods_id__in=ids)
        #获取用户信息
        user = User.objects.get(id=get_session(request,'uid'))
        #创建订单基础信息
        order = Order()
        order.order_addr = user.user_addr
        order.order_recv = user.user_recv
        order.order_pay = goods_pay
        order.order_user = user
        #订单编号
        order.order_number = str(user.id) + str(int(time.time())) + str(random.randint(1000,9999))
        order.save()

        #创建订单商品详细信息
        for cart in carts:
            detail = OrderDetail()
            detail.order = order
            detail.detail_amount = cart.cart_amount
            detail.detail_goodsid = cart.cart_goods_id
            detail.detail_img = cart.cart_goods.goods_image
            detail.detail_price = cart.cart_goods.goods_price
            detail.detail_name = cart.cart_goods.goods_name
            detail.detail_unit = cart.cart_goods.goods_unit
            detail.save()
        #删除购物车里相关的数据
        carts.delete()

        transaction.savepoint_commit(save_point) # 成功提交事务
    except:
        transaction.savepoint_rollback(save_point) # 失败滚回保存点
        return JsonResponse({'ret': 0})

    return JsonResponse({'ret':1})

templates/order/place_order.html
{# 继承父模板 #}
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load goods_filters %}

{% block header_js %}
    <script>
        $(
            //js ready
            function () {
                $("#order_btn").click(
                    function () {
                        goods_list = $(this).attr('goods_list');//获得商品列表
                        pay_style = $('input[name="pay_style"]:checked').val(); //获得支付方式
                        csrf_value = $('input[name="csrfmiddlewaretoken"]').val();
                        $.post(
                            '{% url 'order:order_handle' %}', {
                                'ids': goods_list,
                                'pay': pay_style,
                                'csrfmiddlewaretoken': csrf_value
                            }, function (data) {
                                if (data.ret) {

                                    localStorage.setItem('order_finish', 2);

                                    $('.popup_con').fadeIn('fast', function () {

                                        setTimeout(function () {
                                            $('.popup_con').fadeOut('fast', function () {
                                                window.location.href = '{% url 'users:user_center_order' %}';
                                            });
                                        }, 3000)

                                    });
                                } else {
                                    alert('订单提交失败');
                                }
                            }
                        );


                    }
                )
            }
        )
    </script>
{% endblock header_js %}


{% block body %}
    {# 上方用户状态条 #}
    {% include 'common/status.html' %}

    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
        <div class="search_con fr">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
    </div>

    <h3 class="common_title">确认收货地址</h3>

    <div class="common_list_con clearfix">
        <dl>
            <dt>寄送到：</dt>
            <dd><input type="radio" name="" checked="">{{ user.user_addr }} （{{ user.user_name }}
                收） {{ user.user_tele }}</dd>
        </dl>
        <a href="{% url 'users:user_center_site' %}" class="edit_site">编辑收货地址</a>

    </div>

    <h3 class="common_title">支付方式</h3>
    <div class="common_list_con clearfix">
        <div class="pay_style_con clearfix">
            <input type="radio" name="pay_style" value="1" checked>
            <label class="cash">货到付款</label>
            <input type="radio" name="pay_style" value="2">
            <label class="weixin">微信支付</label>
            <input type="radio" name="pay_style" value="3">
            <label class="zhifubao"></label>
            <input type="radio" name="pay_style" value="4">
            <label class="bank">银行卡支付</label>
        </div>
    </div>

    <h3 class="common_title">商品列表</h3>

    <div class="common_list_con clearfix">
        <ul class="goods_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
        </ul>
        {% for cart in carts %}
            <ul class="goods_list_td clearfix">
                <li class="col01">{{ forloop.counter }}</li>
                <li class="col02"><img src="{% static cart.cart_goods.goods_image|create_goods_image_name %} "></li>
                <li class="col03">{{ cart.cart_goods.goods_name }}</li>
                <li class="col04">{{ cart.cart_goods.goods_unit }}</li>
                <li class="col05">{{ cart.cart_goods.goods_price }}元</li>
                <li class="col06">{{ cart.cart_amount }}</li>
                <li class="col07">{{ cart.total }}元</li>
            </ul>
        {% endfor %}
    </div>

    <h3 class="common_title">总金额结算</h3>

    <div class="common_list_con clearfix">
        <div class="settle_con">
            <div class="total_goods_count">共<em>{{ carts.total_nums }}</em>件商品，总金额<b>{{ carts.total_money }}元</b></div>
            <div class="transit">运费：<b>10元</b></div>
            <div class="total_pay">实付款：<b>{{ carts.total_money }}元</b></div>
        </div>
    </div>

    <div class="order_submit clearfix">
        {% csrf_token %}
        <a href="javascript:;" id="order_btn" goods_list="{{ goods_ids_string }}">提交订单</a>
    </div>


    <div class="popup_con">
        <div class="popup">
            <p>订单提交成功！</p>
        </div>

        <div class="mask"></div>
    </div>
{% endblock body %}